name: Transcribe

on: workflow_dispatch

jobs:
    transcribe:
        name: Transcribe
        runs-on: ubuntu-latest
        timeout-minutes: 2880
        steps:
            - uses: actions/checkout@v2
            - uses: FedericoCarboni/setup-ffmpeg@v2
            - run: bash setup.sh
            - name: Setup | Rust
              uses: ATiltedTree/setup-rust@v1
              with:
                  rust-version: nightly
            - run: cargo run --release
              env:
                  USERNAME: ${{ secrets.USERNAME }}
                  PASSWORD: ${{ secrets.PASSWORD }}

            - run: bash transcribe.sh
