name: Transcribe

on: workflow_dispatch

jobs:
    transcribe:
        name: Transcribe
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Download if not cached
              run: bash setup.sh
            - uses: FedericoCarboni/setup-ffmpeg@v2
            - run: bash setup.sh
            - name: Setup | Rust
              uses: ATiltedTree/setup-rust@v1
              with:
                  rust-version: nightly
            - run: cargo run --release
              env:
                  USERNAME: ${{ secrets.USERNAME }}
                  PASSWORD: ${{ secrets.PASSWORD }}
            - run: bash transcribe.sh
            - run: git add transcribed.txt output
            - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
            - run: git config --global user.name "github-actions[bot]"
            - run: git commit -m "Transcribe"
            - run: git push
