name: Transcribe

on: workflow_dispatch

jobs:
    transcribe:
        name: Transcribe
        runs-on: ubuntu-latest
        steps:
            - name: Setup | Rust
              uses: ATiltedTree/setup-rust@v1
              with:
                  rust-version: nightly
            - run: cargo run --release
              env:
                  USERNAME: ${{ secrets.USERNAME }}
                  PASSWORD: ${{ secrets.PASSWORD }}

            - uses: FedericoCarboni/setup-ffmpeg@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - run: pip install -U openai-whisper
            - run: for filename in videos/*.mp4; do |
                  whisper "$filename" --model large-v2 --model_dir models/ --output_dir outputs/ --output_format vtt --language de |
                  done
