name: Transcribe

on: workflow_dispatch

jobs:
    transcribe:
        name: Transcribe
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: FedericoCarboni/setup-ffmpeg@v2
            - run: bash setup.sh
            - name: Setup | Rust
              uses: ATiltedTree/setup-rust@v1
              with:
                  rust-version: nightly
            - run: cargo run --release
              env:
                  USERNAME: ${{ secrets.USERNAME }}
                  PASSWORD: ${{ secrets.PASSWORD }}
            - run: if [ -z "$(ls -A wavs)" ]; then exit 1; fi
            - run: bash transcribe.sh
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  add-paths: |
                      transcribed.txt
                      outputs
                  commit-message: Transcribe
                  branch-suffix: timestamp
                  branch: transcribe
                  delete-branch: true
            - run: gh workflow run main.yml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
